2024-10-07 15:21:23,530 | INFO | "test_run" выполнен успешно
2024-10-07 15:21:23,530 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "F:\python\project\pythonProject\module_12\module_12_4\module_12_4.py", line 72, in test_run
    test2 = Runner(34, 5)
            ^^^^^^^^^^^^^
  File "F:\python\project\pythonProject\module_12\module_12_4\module_12_4.py", line 13, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-07 15:21:23,530 | INFO | "test_walk" выполнен успешно
2024-10-07 15:21:23,531 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "F:\python\project\pythonProject\module_12\module_12_4\module_12_4.py", line 63, in test_walk
    test1 = Runner('Вося', -8)
            ^^^^^^^^^^^^^^^^^^
  File "F:\python\project\pythonProject\module_12\module_12_4\module_12_4.py", line 18, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -8
